/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        wine: {
          50:  '#fdf2f4',
          100: '#fae0e4',
          200: '#f5c0ca',
          300: '#ee91a2',
          400: '#e45872',
          500: '#d42e4f',
          600: '#b81d3c',
          700: '#9a1633',
          800: '#72102a',
          900: '#5c0d22',
          950: '#3a0616',
        },
        gold: {
          300: '#e8c96b',
          400: '#d4a847',
          500: '#c9a84c',
          600: '#b8962a',
          700: '#9a7d1e',
        },
        anthracite: {
          50:  '#f6f7f7',
          100: '#e2e4e4',
          200: '#c5c9ca',
          300: '#a0a7a8',
          400: '#7a8486',
          500: '#5f6b6d',
          600: '#4a5558',
          700: '#3d4547',
          800: '#2c3234',
          900: '#1e2426',
          950: '#111516',
        },
        cream: '#f5f0e8',
      },
      fontFamily: {
        serif:  ['Playfair Display', 'Georgia', 'serif'],
        sans:   ['Inter', 'system-ui', 'sans-serif'],
        script: ['Tangerine', 'cursive'],
      },
      boxShadow: {
        'gold':        '0 4px 24px rgba(201,168,76,0.25)',
        'gold-lg':     '0 8px 48px rgba(201,168,76,0.35)',
        'wine':        '0 4px 24px rgba(114,16,42,0.4)',
        'wine-lg':     '0 8px 48px rgba(114,16,42,0.5)',
        'card':        '0 2px 16px rgba(0,0,0,0.08)',
        'card-hover':  '0 8px 32px rgba(0,0,0,0.14)',
        'glass':       '0 8px 32px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.1)',
        'glow-gold':   '0 0 40px rgba(201,168,76,0.3)',
        'glow-wine':   '0 0 40px rgba(114,16,42,0.5)',
      },
      animation: {
        'fade-in':       'fadeIn 0.4s ease-out',
        'fade-in-up':    'fadeInUp 0.6s ease-out',
        'fade-in-down':  'fadeInDown 0.5s ease-out',
        'slide-up':      'slideUp 0.35s ease-out',
        'slide-in-right':'slideInRight 0.5s ease-out',
        'scale-in':      'scaleIn 0.4s ease-out',
        'float':         'float 6s ease-in-out infinite',
        'float-slow':    'float 9s ease-in-out infinite',
        'float-delayed': 'float 7s ease-in-out infinite 2s',
        'shimmer':       'shimmer 2.5s linear infinite',
        'pulse-gold':    'pulseGold 3s ease-in-out infinite',
        'spin-slow':     'spin 12s linear infinite',
        'gradient-x':    'gradientX 8s ease infinite',
        'count-up':      'countUp 1.5s ease-out',
        'draw-line':     'drawLine 1.2s ease-out forwards',
        'bounce-subtle': 'bounceSubtle 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:        { from: { opacity: 0 }, to: { opacity: 1 } },
        fadeInUp:      { from: { opacity: 0, transform: 'translateY(24px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        fadeInDown:    { from: { opacity: 0, transform: 'translateY(-16px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideUp:       { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideInRight:  { from: { opacity: 0, transform: 'translateX(24px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        scaleIn:       { from: { opacity: 0, transform: 'scale(0.92)' }, to: { opacity: 1, transform: 'scale(1)' } },
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%':      { transform: 'translateY(-18px) rotate(2deg)' },
          '66%':      { transform: 'translateY(-8px) rotate(-1deg)' },
        },
        shimmer: {
          from: { backgroundPosition: '-200% center' },
          to:   { backgroundPosition: '200% center' },
        },
        pulseGold: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(201,168,76,0.2)' },
          '50%':      { boxShadow: '0 0 40px rgba(201,168,76,0.5)' },
        },
        gradientX: {
          '0%, 100%': { backgroundSize: '200% 200%', backgroundPosition: 'left center' },
          '50%':      { backgroundSize: '200% 200%', backgroundPosition: 'right center' },
        },
        countUp: {
          from: { opacity: 0, transform: 'translateY(8px)' },
          to:   { opacity: 1, transform: 'translateY(0)' },
        },
        drawLine: {
          from: { transform: 'scaleX(0)', transformOrigin: 'left' },
          to:   { transform: 'scaleX(1)', transformOrigin: 'left' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':      { transform: 'translateY(-6px)' },
        },
      },
      backgroundImage: {
        'gradient-radial':    'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':     'conic-gradient(var(--tw-gradient-stops))',
        'shimmer-gold':       'linear-gradient(90deg, transparent, rgba(201,168,76,0.4), transparent)',
        'noise':              "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.05'/%3E%3C/svg%3E\")",
      },
    },
  },
  plugins: [],
}
